create deploy task , publish task.

diff --git a/ci/publish.yml b/ci/publish.yml
--- a/ci/publish.yml
+++ b/ci/publish.yml
@@ -14,16 +14,19 @@ run:
     - -c
     - |
 
+      if ! apt-get update && apt-get install -y jq
+      then
+        echo 'ERROR: jq install failed'
+        exit 1
+      fi
+
       cd protect-js-sdk-master
 
       # prevent infinite loop from version bumping via ci
       if git log | head -n 2 | tail -n 1 | grep 'Concourse CI'
       then
-        echo "i am stopping the build"
         exit 0
       fi
-
-      echo "i am not stopping the build"
 
       git config --global user.email 'noreply@ns8.com'
       git config --global user.name 'Concourse CI'
@@ -50,4 +53,7 @@ run:
       echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
       ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub 
 
-      git push origin HEAD:master
+      VERSION="$(jq .version package.json | sed s/\“//g)"
+      git tag "$VERSION"
+
+      git push origin --tags HEAD:master
