Adding logic to build versioned JS file for each publish event CH-17961

diff --git a/ci/publish.yml b/ci/publish.yml
--- a/ci/publish.yml
+++ b/ci/publish.yml
@@ -13,7 +13,10 @@ run:
   args:
     - -c
     - |
-
+      # install JQ for easier version parsing
+      apt-get update
+      apt-get -y install jq
+      
       cd protect-sdk-client-master
 
       # prevent infinite loop from version bumping via ci
@@ -27,6 +30,12 @@ run:
 
       echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
 
+      if ! yarn install
+      then
+        echo "ERROR: yarn install failed" 
+        exit 1
+      fi
+      
       if ! yarn version --patch
       then
         echo "ERROR: yarn version patch update failed"
@@ -38,6 +47,15 @@ run:
         echo "ERROR: yarn publish failed"
         exit 1
       fi
+
+      if ! yarn build:prod
+      then
+        echo "ERROR: yarn build:prod failed"
+        exit 1
+      fi
+
+      current_version=$(yarn info --json | jq -r '.["data"]["dist-tags"]["latest"]')
+      cp dist/protect.min.js dist/protect-$current_version.min.js
 
       mkdir ~/.ssh && chmod 700 ~/.ssh
 
