Improve Concourse pipeline tasks

diff --git a/ci/publish.yml b/ci/publish.yml
--- a/ci/publish.yml
+++ b/ci/publish.yml
@@ -6,17 +6,33 @@ image_resource:
   source: { repository: node, tag: "12" }
 
 inputs:
-  - name: protect-js-sdk
+  - name: protect-js-sdk-master
 
 run:
-  path: /bin/sh
+  path: /bin/bash
   args:
     - -c
     - |
 
+      if ! apt-get update && apt-get install -y jq
+      then
+        echo 'ERROR: jq install failed'
+        exit 1
+      fi
+
+      cd protect-js-sdk-master
+
+      # prevent infinite loop from version bumping via ci
+      if git log | head -n 2 | tail -n 1 | grep 'Concourse CI'
+      then
+        exit 0
+      fi
+
+      git config --global user.email 'noreply@ns8.com'
+      git config --global user.name 'Concourse CI'
+
       echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
 
-      cd protect-js-sdk
 
       if ! yarn version --patch
       then
@@ -24,8 +40,20 @@ run:
         exit 1
       fi
 
-      if ! yarn publish
+      if ! npm publish
       then
         echo "ERROR: yarn publish failed"
         exit 1
       fi
+
+      mkdir ~/.ssh && chmod 700 ~/.ssh
+
+      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
+
+      echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
+      ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
+
+      VERSION="$(jq .version package.json | sed s/\“//g)"
+      git tag "$VERSION"
+
+      git push origin --tags HEAD:master
