Clean up readme, add badge. Add work-in-progress CI test.yml for concourse.

diff --git a/ci/test.yml b/ci/test.yml
--- a/ci/test.yml
+++ b/ci/test.yml
@@ -1,45 +1,32 @@
 ---
-resources:
+platform: linux
+
+image_resource:
+  type: registry-image
+  source: { repository: node, tag: "12" }
+
+inputs:
   - name: protect-js-sdk
-    type: git
-    icon: github-circle
-    source:
-      uri: https://github.com/ns8inc/protect-js-sdk.git
-jobs:
-  - name: test-and-lint
-    public: true
-    plan:
-      - get: protect-js-sdk
-        trigger: true
-      - task: test
-        config:
-          platform: linux
-          image_resource:
-            type: registry-image
-            source: { repository: node, tag: "12" }
-          inputs:
-            - name: protect-js-sdk
-          run:
-            path: /bin/sh
-            args:
-              - -c
-              - |
-                cd protect-js-sdk
-                yarn install 
-                yarn test
-      - task: lint
-        config:
-          platform: linux
-          image_resource:
-            type: registry-image
-            source: { repository: node, tag: "12" }
-          inputs:
-            - name: protect-js-sdk
-          run:
-            path: /bin/sh
-            args:
-              - -c
-              - |
-                cd protect-js-sdk
-                yarn install 
-                yarn lint
+
+run:
+  path: /bin/sh
+  args:
+    - -c
+    - |
+      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
+      cd protect-js-sdk
+      if ! yarn install
+      then
+        echo "ERROR: yarn install failed" 
+        exit 1
+      fi
+      if ! yarn lint
+      then
+        echo "ERROR: yarn lint failed" 
+        exit 1
+      fi
+      if ! yarn test
+      then
+        echo "ERROR: yarn test failed" 
+        exit 1
+      fi
